version: '3.7'
networks:
  dspacenet:
services:
  dspace-angular:
    container_name: dspace-angular
    environment:
      DSPACE_HOST: 127.0.0.1
      DSPACE_NAMESPACE: /
      DSPACE_PORT: 4000
      DSPACE_SSL: 'false'
      DSPACE_REST_HOST: rest.dspace.bibbox.org
      DSPACE_REST_PORT: 80
      DSPACE_REST_NAMESPACE: /server/api
      DSPACE_REST_SSL: 'false'
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      dspacenet:
    ports:
    - published: 4000
      target: 4000
    - published: 9876
      target: 9876
    stdin_open: true
    tty: true
    networks:
      dspacenet:
    ports:
    - published: 4000
      target: 4000
    - published: 9876
      target: 9876
    stdin_open: true
    tty: true
    volumes:
    - ./environment.dev.ts:/app/src/environments/environment.dev.ts
